[package]
name = "kraken"

authors.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
# WORKSPACE 
trading_api =  { workspace = true }

# EXTERNAL
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }

